'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Agent_Type
    Public Property Agent_Type_ID As Integer
    Public Property Agent_Type_Name As String
    Public Property Agent_Type_Description As String

End Class
